#!/usr/bin/python3.9
# Данная игра разрабатывалась сразу с учетом 
# графического интерфейса, по этому быстрее всего было 
# просто оставить функционал прослушивания клавиатуры.
# А поскольку основной средой исполнения была выбрана ОС/Linux 
# понадобилось подключить библиотеку curses.

import curses,json,random,time,sys

e1 = 0 

with open('./wordlist','r') as wf:
    words = json.load(wf)

def game(win):
    z = 4 # Вода
    s = 0 # Расстояние
    c = 0
    c1 = 0
    q = 0
    E = 15 # Выносливость
    global e1

    curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLUE)
    win.bkgd(' ', curses.color_pair(1) | curses.A_BOLD)
    win.nodelay(True)
    key=""
    win.clear()
    win.addstr("CAMEL\n")
    win.addstr("Creative Computing\n")
    win.addstr("Morristown, New Jersey\n")
    win.addstr("Press \"s\" to start\n")
    while True:
        try:
            key = win.getkey()
            if key == 'q':
                break
            if key == 's':
                win.clear()
                win.addstr(words['1'])
            elif key == 'y':
                win.addstr(words['2'])
            elif key == 'n':
                win.addstr(words['3'])
            elif key == '1':
                z-=1
                E = 15
                win.clear()
                win.addstr('Залишилося води: '+str(z)+'\n')
                win.addstr('Сили відновлені, можна продовжувати шлях')
            elif key == '2':
                s += random.randint(1,3) + 2
                E -= random.randint(1,2) + 1
                win.clear()
                win.addstr('Пройдена вiдстань: '+str(s)+'\n')
                win.addstr('Залишилось сил: '+str(E))
            elif key == '3':
                s += random.randint(3,9) + 2
                E -= random.randint(2,4) + 1
                win.clear()
                win.addstr('Пройдена вiдстань: '+str(s))
                win.addstr('Залишилось сил: '+str(E))
            elif key == '4':
                d = random.randint(1,16)
                if d < 13:
                    win.clear()
                    win.addstr('Тут небезпечно')
                else:
                    E = 15
                    win.clear()
                    win.addstr('Сили відновлені, можна продовжувати шлях')
                if d < 12:
                    win.addstr('Верблюду не подобається це місце')
                    win.addstr('\nThis is unsafety place! Find another one.\n')
                else:
                    E = 15
                    win.clear()
                    win.addstr('Сили відновлені, можна продовжувати шлях')
                    e1 = random.randint(1,8)+2
                if e1 >= 10:
                    win.clear()
                    Trap()
                elif key == '6':
                    h = random.randint(1,10)+2
                    if h == 10:
                        win.clear()
                        win.addstr('Допомога прибула, вас знайшли непритомні')
                        win.addstr(words['16'])
                        z += 1
                        E = 15
                    else:
                        win.clear()
                        win.addstr('Ви і ваш верблюд загинули у пустелі')
                        win.addstr('You dead in the desert')
                        Loose()
            
            
                o = random.randint(1,100)
                if o > 97:
                    E = 15
                    z += random.randint(2,3)+1
                    win.clear()
                    win.addstr(words['12'])
                    win.addstr('Ви знайшли оазис, запаси води поповнені')
            
                if key == '5':
                    win.addstr(words['15'].format(z,E,s))
            
                if s > 200:
                    win.clear()
                    win.addstr('Выигрыш')
                    win.addstr(words['6'])
                    time.sleep(2)
                    sys.exit(0)
                    
                if z == 1:
                    win.clear()
                    win.addstr('Вода')
                    win.addstr(words['4'])
                elif z < 0:
                    win.clear()
                    win.addstr('Ви і ваш верблюд загинули у пустелі')
                    Loose()
                if E <= 0:
                    win.clear()
                    win.addstr('Потрібен відпочинок!')
                    if E < 0:
                        win.clear()
                        win.addstr(words['7'])
                        Loose()
                elif z < 0:
                    win.addstr(words['5'])
        except Exception as e:
            pass

def Loose():
    win.clear()
    win.addstr('Проигрыш')
    time.sleep(2)
    sys.exit(0)

def Trap():
    global e1,z
    win.clear()
    win.addstr('Ви потрапили в полон!\n\
Що робити? №7 утекти Чи №8 чекати на викуп\n')
    win.addstr(words['10'])
    if key == '7':
        e1 = random.randint(12,18)+2
        if e1 >= 12:
            win.clear()
            win.addstr('Вам вдалося вибратися з полону')
            win.addstr(words['13'])
        else:
            win.clear()
            win.addstr('Вас з\'їли берберки')
            win.addstr(words['11'])
            Loose()
    elif key == '8':
        e1 = random.randint(12,18)+2
        if e1 >= 16:
            win.clear()
            win.addstr(e1)
            win.addstr('Місцевий шейх вирішив вас викупити')
            win.addstr(words['9'])
            E += random.randint(1,5)
            win.addstr('Сили відновлені, можна продовжувати шлях')
            z += random.randint(1,3)
            win.addstr('Запаси води поповнені: '+str(z))
        else:
            win.clear()
            win.addstr('Аборигени забрали вас у рабство')
            win.addstr(words['14'])
            Loose()
            
curses.wrapper(game)
